app:
    name: Dux
    debug: true
    cache: false
    secret: e4402d4189ab8e16735e45a130632e16
    domain: 'http://localhost'
clock: false
lang: zh-CN
sideType: app
vite:
    dev: false
    port: 5173
