app:
    name: Dux
    debug: true
    cache: false
    secret: a9dfda61e965d5101dfbf31e959fe096
    domain: 'http://duxcms.test'
clock: false
lang: zh-CN
vite:
    dev: false
    port: 5173
manage:
    indexName: cms
    baiduMap:
